version: '3'

services:
  banco:
    build:
      context: ./
    container_name: banco_container
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
    restart: unless-stopped
    networks:
      - app-network

  tarefas:
    build:
      context: ../tarefas
    container_name: tarefas_container
    ports:
      - "8081:8081"
    environment:
      - server.port=8081
    depends_on:
      - banco
    restart: unless-stopped
    networks:
      - app-network

  atribuicao:
    build:
      context: ../atribuicao
    container_name: atribuicao_container
    ports:
      - "8082:8082"
    environment:
      - server.port=8082
    depends_on:
      - banco
      - tarefas
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
