apiVersion: apps/v1
kind: Deployment
metadata:
  name: atribuicao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atribuicao
  template:
    metadata:
      labels:
        app: atribuicao
    spec:
      containers:
      - name: atribuicao
        image: mateusol22/banco-atribuicao:latest
        ports:
        - containerPort: 8082
