apiVersion: v1
kind: Service
metadata:
  name: atribuicao
spec:
  type: NodePort
  selector:
    app: atribuicao
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30008
