apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
      - name: banco
        image: mateusol22/banco-banco:latest
        ports:
        - containerPort: 8080
