apiVersion: v1
kind: Service
metadata:
  name: tarefas
spec:
  type: NodePort
  selector:
    app: tarefas
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarefas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarefas
  template:
    metadata:
      labels:
        app: tarefas
    spec:
      containers:
        - name: tarefas
          image: mateusol22/tarefas:latest
          ports:
            - containerPort: 8081
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"

