apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarefas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarefas
  template:
    metadata:
      labels:
        app: tarefas
    spec:
      containers:
      - name: tarefas
        image: mateusol22/banco-tarefas:latest
        ports: 
        - containerPort: 8081
